uploads = []
generated = []

[[outputs]]
id = "13sQXXp3jwbn_CVof0GHR"
uri = "file://gibifinder-project.tar.gz"
type = "unspecified"
title = "GibiFinder — Projeto Completo"

[[outputs]]
id = "ckZh0NMeX1Z_4T-Szv60R"
uri = "file://gibifinder-project.zip"
type = "unspecified"
title = "GibiFinder — Projeto Completo (.zip)"
